### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by gautamkrishnar** [MozillaKeralaDreamTeam/SOPs#1]
If you are planning to add all contributors to this Org, I think you guys need to create something just like this:
https://github.com/mdckerala/Join-Us

So that interested peoples can comment their github username in an issue thread. similar to this: https://github.com/mdckerala/Join-Us/issues/1

**Comment by nikhiljohn10** [comment]
Thank you for the suggestion :+1: 

We are currently not expanding the team. We are going through a beginning phase here. After we achieve a structure as we try to achieve goals, then this team will be open to public to join.
